delete from COMPANY;
delete from ROLE_FA;
delete from LOCATION;
delete from INDUSTRY;
delete from INDUSTRY_SUBGROUP_FA;
delete from CANDIDATE;
delete from COMPANY_REVIEW_RATING;
delete from COMPANY_REVIEW_WORK_REASON;
delete from COMPANY_REVIEW_SUCCESS_SKILLS;
delete from COMPANY_INTERVIEW;
delete from CANDIDATE_LEVEL;
delete from INTERVIEW_QUESTION_CATEGORY;
delete from INDUSTRY_ROLE_SALARY_BAND;
delete from COMPANY_ROLE_SALARY_BAND;
delete from INTERVIEW_QUESTION_CATEGORY_FACT;
delete from JOBBUZZ_TJ_TRACK;
delete from JB_KPI_FACT;
delete from ENTITY_TYPE_MASTER;
delete from SUB_ENTITY_TYPE_MASTER;
delete from ACTIVITY_TYPE_MASTER;
delete from ACTIVITY_FACT;
delete from COMPANY_OVERALL_RATING;
delete from COMPANY_REVIEW_QNA;
delete from FOLLOW_COMPANY_FACT;
delete from COMMENTS_FACT;

load data local infile '/opt/dw_data/data/jobbuzz/COMPANY.txt' into table COMPANY fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/ROLE_FA.txt' into table ROLE_FA fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/LOCATION.txt' into table LOCATION fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/INDUSTRY.txt' into table INDUSTRY fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/INDUSTRY_SUBGRP_FA.txt' into table INDUSTRY_SUBGROUP_FA fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/CANDIDATE.txt' into table CANDIDATE fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/COMPANY_REVIEW_RATING.txt' into table COMPANY_REVIEW_RATING fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/COMPANY_REVIEW_WORK_REASON.txt' into table COMPANY_REVIEW_WORK_REASON fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/COMPANY_REVIEW_SUCCESS_SKILLS.txt' into table COMPANY_REVIEW_SUCCESS_SKILLS fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/COMPANY_INTERVIEW.txt' into table COMPANY_INTERVIEW fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/COMPANY_INTERVIEW_QUESTION_CATEGORY.txt' into table INTERVIEW_QUESTION_CATEGORY_FACT fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/LEVEL_MAS.txt' into table CANDIDATE_LEVEL fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/INTERVIEW_QUESTION_CATEGORY_MAS.txt' into table INTERVIEW_QUESTION_CATEGORY fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/INDUSTRY_ROLE_SALARY_BAND.txt' into table INDUSTRY_ROLE_SALARY_BAND fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/COMPANY_ROLE_SALARY_BAND.txt' into table COMPANY_ROLE_SALARY_BAND fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/TJ_TRACK.txt' into table JOBBUZZ_TJ_TRACK  fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/ENTITY_TYPE_MASTER.txt' into table ENTITY_TYPE_MASTER fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/SUB_ENTITY_TYPE_MASTER.txt' into table SUB_ENTITY_TYPE_MASTER fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/ACTIVITY_TYPE_MASTER.txt' into table ACTIVITY_TYPE_MASTER fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/ACTIVITY_FACT.txt' into table ACTIVITY_FACT fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/COMPANY_OVERALL_RATING.txt' into table COMPANY_OVERALL_RATING fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/COMPANY_REVIEW_QNA.txt' into table COMPANY_REVIEW_QNA fields terminated by ',' enclosed by '"' lines terminated by '\n';

load data local infile '/opt/dw_data/data/jobbuzz/FOLLOW_COMPANY_FACT.txt' into table FOLLOW_COMPANY_FACT  fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/COMMENTS_FACT.txt' into table COMMENTS_FACT fields terminated by ',' enclosed by '"' lines terminated by '\n';
load data local infile '/opt/dw_data/data/jobbuzz/JB_KPI_FACT.txt' into table JB_KPI_FACT fields terminated by ',' enclosed by '"' lines terminated by '\n';
