#!/bin/ksh
set -x

cd /home/dwhuser/generic_etl/ksh_scripts

input=$3
isFile=`echo $input | egrep -i '\.txt|\.log|\.cron|\.dmp'`

if [[ $isFile != "" ]]; then
    input_file=`cat $input`
    perl $HOME/generic_etl/ksh_scripts/mail.pl "$1" " $2" "$input_file"
else
    perl $HOME/generic_etl/ksh_scripts/mail.pl "$1" " $2"  "$3"
fi
exit 1
