#!/bin/bash

cd ${HOME}/generic_etl/wip

zip WEEKLY_REPORT_DEMO_$pth WEEKLY_Active_Client_details_31_June_2009_demo.txt WEEKLY_ActiveClient_Active_paid_Database_service_demo.txt WEEKLY_ActiveClient_Active_paid_Job_posting_service_demo.txt WEEKLY_ActiveClient_Active_paid_Visibility_service_demo.txt WEEKLY_ActiveClient_Active_paid_Other_service_demo.txt WEEKLY_ActiveClient_Active_trial_Database_service_demo.txt WEEKLY_ActiveClient_Active_trial_Job_posting_service_demo.txt WEEKLY_ActiveClient_Active_trial_Visibility_service_demo.txt WEEKLY_ActiveClient_Active_trial_Other_service_demo.txt WEEKLY_ActiveClient_Deactive_paid_Database_service_demo.txt WEEKLY_ActiveClient_Deactive_paid_Job_posting_service_demo.txt WEEKLY_ActiveClient_Deactive_paid_Visibility_service_demo.txt WEEKLY_ActiveClient_Deactive_paid_Other_service_demo.txt WEEKLY_ActiveClient_Deactive_trial_Database_service_demo.txt WEEKLY_ActiveClient_Deactive_trial_Job_posting_service_demo.txt WEEKLY_ActiveClient_Deactive_trial_Visibility_service_demo.txt WEEKLY_ActiveClient_Deactive_trial_Other_service_demo.txt

mv WEEKLY_REPORT_DEMO.zip ${HOME}/generic_etl/data_archive/weekly_report/ 
