#!/bin/bash

cd ${HOME}/generic_etl/wip
mkdir ${HOME}/generic_etl/data_archive/weekly_report/$pth

zip WEEKLY_REPORT ALL_Weekely_REPActiveClient_Details_NEW_changed.txt ALL_Weekely_REPActiveClient_Details.txt ALL_Weekely_REPActiveClient_Active_paid_Database_service.txt ALL_Weekely_REPActiveClient_Active_paid_Job_posting_service.txt ALL_Weekely_REPActiveClient_Active_paid_Visibility_service.txt ALL_Weekely_REPActiveClient_Active_paid_Other_service.txt ALL_Weekely_REPActiveClient_Active_trial_Database_service.txt ALL_Weekely_REPActiveClient_Active_trial_Job_posting_service.txt ALL_Weekely_REPActiveClient_Active_trial_Visibility_service.txt ALL_Weekely_REPActiveClient_Active_trial_Other_service.txt 

mv WEEKLY_REPORT.zip ${HOME}/generic_etl/data_archive/weekly_report/$pth/

rm -f ALL_Weekely_REPActiveClient_Details_NEW_changed.txt ALL_Weekely_REPActiveClient_Details.txt ALL_Weekely_REPActiveClient_Active_paid_Database_service.txt ALL_Weekely_REPActiveClient_Active_paid_Job_posting_service.txt ALL_Weekely_REPActiveClient_Active_paid_Visibility_service.txt ALL_Weekely_REPActiveClient_Active_paid_Other_service.txt ALL_Weekely_REPActiveClient_Active_trial_Database_service.txt ALL_Weekely_REPActiveClient_Active_trial_Job_posting_service.txt ALL_Weekely_REPActiveClient_Active_trial_Visibility_service.txt ALL_Weekely_REPActiveClient_Active_trial_Other_service.txt 
