MERGE INTO CALLING_DNC_DATA AS cdd  USING CALLING_DNC_DATA_STAGE cdds ON (cdd.MOBILE_NO = cdds.MOBILE_NO) WHEN NOT MATCHED THEN    INSERT (cdd.MOBILE_NO,cdd.CENTER_NAME) values (cdds.MOBILE_NO,'iEnergizer')

