MERGE INTO CALLING_DNC_DATA AS cdd  USING CALLING_DNC_DATA_STAGE cdds ON (cdd.MOBILE_NO = cdds.MOBILE_NO) WHEN NOT MATCHED THEN    INSERT (cdd.MOBILE_NO,cdd.CENTER_NAME) values (cdds.MOBILE_NO,'Effort')

MERGE INTO CALLING_RPC_DATA crd USING (select max(UPDATED_DATE) as UPDATED_DATE, max(CENTER_NAME) as CENTER_NAME, max(CAMPAIGN_NAME) as CAMPAIGN_NAME, MOBILE_NO , max(STATUS) as STATUS, max(DISPOSITION_STATUS) as DISPOSITION_STATUS from CALLING_RPC_DATA_STAGE group by MOBILE_NO) crds ON (crd.MOBILE_NO = crds.MOBILE_NO) WHEN NOT MATCHED THEN    INSERT (crd.UPDATED_DATE, crd.CENTER_NAME, crd.CAMPAIGN_NAME, crd.MOBILE_NO, crd.STATUS, crd.DISPOSITION_STATUS)    VALUES (crds.UPDATED_DATE,crds.CENTER_NAME,crds.CAMPAIGN_NAME,crds.MOBILE_NO,crds.STATUS,crds.DISPOSITION_STATUS)

