select uau.MODIFIED_DATE,VWA.WIDGET_ID, VWA.EDIT_PRECEDENCE,WSM.WIDGET_STATUS_ID, 
       AVG(VWA.WEIGHT) WIDGET_WEIGHT ,count(1) USER_COUNT
from
(
  select ua.MODIFIED_DATE,U.LOGIN_SRL_NO,ua.LAST_MODIFIED_TIME
  from
  (
    select date(LAST_MODIFIED_TIME) MODIFIED_DATE,LOGIN_SRL_NO,LAST_MODIFIED_TIME
    from USER_AD
    where LAST_MODIFIED_TIME between char((current date - 1 day),ISO)||' 00:00:00.00' and char((current date - 1 day),ISO)||' 23:59:59.00' 
  ) ua,USER U
  where U.LOGIN_SRL_NO = UA.LOGIN_SRL_NO
  and U.LOGIN_CREATE_DATE != current date - 1 day
) uau, USER_WIDGETS UW, 
     tcadmin.VW_VERTICAL_WIDGET_APPLICABILITY VWA, 
     tcadmin.WIDGET_STATUS_MASTER WSM
where uau.LOGIN_SRL_NO = UW.LOGIN_SRL_NO
  and VWA.WIDGET_ID = UW.WIDGET_ID 
  and WSM.WIDGET_STATUS_ID = UW.WIDGET_STATUS_ID 
  and DATE(UW.DATE_MODIFIED) = DATE(uau.LAST_MODIFIED_TIME) 
group by uau.MODIFIED_DATE,VWA.WIDGET_ID, VWA.EDIT_PRECEDENCE,WSM.WIDGET_STATUS_ID with ur;
