export to /home/datareq/generic_etl/data_files/WIDGET_CREATE_FACT.txt of del modified by coldel, datesiso select U.LOGIN_CREATE_DATE,VWA.WIDGET_ID, VWA.REGISTRATION_PRECEDENCE,WSM.WIDGET_STATUS_ID, AVG(VWA.WEIGHT) WIDGET_WEIGHT, count(1) USER_COUNT from TCUSER.USER U ,USER_WIDGETS UW, tcadmin.VW_VERTICAL_WIDGET_APPLICABILITY VWA, tcadmin.WIDGET_STATUS_MASTER WSM where U.LOGIN_CREATE_DATE = current date - 1 day AND U.LOGIN_SRL_NO = UW.LOGIN_SRL_NO AND VWA.WIDGET_ID = UW.WIDGET_ID AND WSM.WIDGET_STATUS_ID = UW.WIDGET_STATUS_ID Group by U.LOGIN_CREATE_DATE,VWA.WIDGET_ID, VWA.REGISTRATION_PRECEDENCE,WSM.WIDGET_STATUS_ID Order by VWA.REGISTRATION_PRECEDENCE with ur

export to /home/datareq/generic_etl/data_files/WIDGET_UPDATE_FACT.txt of del modified by coldel, datesiso select uau.MODIFIED_DATE,VWA.WIDGET_ID, VWA.EDIT_PRECEDENCE,WSM.WIDGET_STATUS_ID,        AVG(VWA.WEIGHT) WIDGET_WEIGHT ,count(1) USER_COUNT from (   select ua.MODIFIED_DATE,U.LOGIN_SRL_NO,ua.LAST_MODIFIED_TIME   from    (     select date(LAST_MODIFIED_TIME) MODIFIED_DATE,LOGIN_SRL_NO,LAST_MODIFIED_TIME     from USER_AD     where LAST_MODIFIED_TIME between char((current date - 1 day),ISO)||' 00:00:00.00' and char((current date - 1 day),ISO)||' 23:59:59.00'    ) ua,USER U   where U.LOGIN_SRL_NO = UA.LOGIN_SRL_NO   and U.LOGIN_CREATE_DATE != current date - 1 day ) uau, USER_WIDGETS UW,       tcadmin.VW_VERTICAL_WIDGET_APPLICABILITY VWA,       tcadmin.WIDGET_STATUS_MASTER WSM where uau.LOGIN_SRL_NO = UW.LOGIN_SRL_NO   and VWA.WIDGET_ID = UW.WIDGET_ID    and WSM.WIDGET_STATUS_ID = UW.WIDGET_STATUS_ID    and DATE(UW.DATE_MODIFIED) = DATE(uau.LAST_MODIFIED_TIME) group by uau.MODIFIED_DATE,VWA.WIDGET_ID, VWA.EDIT_PRECEDENCE,WSM.WIDGET_STATUS_ID  with ur

--export to /home/datareq/generic_etl/data_files/WIDGET_UPDATE_FACT.txt of del modified by coldel, datesiso select date(UA.LAST_MODIFIED_TIME) MODIFIED_DATE,VWA.WIDGET_ID, VWA.EDIT_PRECEDENCE,WSM.WIDGET_STATUS_ID, AVG(VWA.WEIGHT) WIDGET_WEIGHT, count(1) USER_COUNT from USER U,USER_AD UA,USER_WIDGETS UW, tcadmin.VW_VERTICAL_WIDGET_APPLICABILITY VWA, tcadmin.WIDGET_STATUS_MASTER WSM where UA.LAST_MODIFIED_TIME between char((current date - 1 day),ISO)||' 00:00:00.00' and char((current date - 1 day),ISO)||' 23:59:59.00' AND DATE(UW.DATE_MODIFIED) = DATE(UA.LAST_MODIFIED_TIME) AND U.LOGIN_CREATE_DATE != current date - 1 day  AND U.LOGIN_ID = UA.LOGIN_ID AND U.LOGIN_SRL_NO = UW.LOGIN_SRL_NO AND VWA.WIDGET_ID = UW.WIDGET_ID AND WSM.WIDGET_STATUS_ID = UW.WIDGET_STATUS_ID Group by date(UA.LAST_MODIFIED_TIME),VWA.WIDGET_ID, VWA.EDIT_PRECEDENCE,WSM.WIDGET_STATUS_ID fetch first 2 rows only with ur

export to /home/datareq/generic_etl/data_files/WIDGET_MASTER.txt of del modified by coldel, datesiso select WIDGET_ID, WIDGET_DESC, ACTIVE_STATUS from TCADMIN.WIDGET_MASTER with ur

export to /home/datareq/generic_etl/data_files/WIDGET_STATUS_MASTER.txt of del modified by coldel, datesiso select WIDGET_STATUS_ID, WIDGET_STATUS_DESC from TCADMIN.WIDGET_STATUS_MASTER with ur

export to /home/datareq/generic_etl/data_files/new_resume_profile_complete_fact.txt of del modified by coldel, datesiso select date(current date - 1 day) PROFILE_CREATE_DATE, SUM(CASE WHEN T.profile_complete between 0 and 49 THEN 1 ELSE 0 END) as Band_0_49_Percent, SUM(CASE WHEN T.profile_complete between 50 and 59 THEN 1 ELSE 0 END) as Band_50_59_Percent, SUM(CASE WHEN T.profile_complete between 60 and 69 THEN 1 ELSE 0 END) as Band_60_69_Percent, SUM(CASE WHEN T.profile_complete between 70 and 79 THEN 1 ELSE 0 END) as Band_70_79_Percent, SUM(CASE WHEN T.profile_complete between 80 and 89 THEN 1 ELSE 0 END) as Band_80_89_Percent, SUM(CASE WHEN T.profile_complete between 90 and 99 THEN 1 ELSE 0 END) as Band_90_99_Percent, SUM(CASE WHEN T.profile_complete = 100 THEN 1 ELSE 0 END) as Band_100_Percent from (select sum(um.WEIGHT) + 46 as profile_complete, u.LOGIN_ID from tcuser.user u, tcuser.user_ad ua, tcuser.USER_WIDGETS uw, tcadmin.WIDGET_MASTER um where u.login_create_date = current date - 1 day and ua.login_id = u.login_id and uw.LOGIN_SRL_NO = ua.LOGIN_SRL_NO and uw.resume_id = ua.ad_id and uw.WIDGET_STATUS_ID = 3 and um.WIDGET_ID = uw.WIDGET_ID Group by u.login_id ) T with ur

export to /home/datareq/generic_etl/data_files/edit_resume_profile_complete_fact.txt of del modified by coldel, datesiso select date(current date - 1 day) PROFILE_MODIFY_DATE, SUM(CASE WHEN T.profile_complete between 0 and 49 THEN 1 ELSE 0 END) as Band_0_49_Percent, SUM(CASE WHEN T.profile_complete between 50 and 59 THEN 1 ELSE 0 END) as Band_50_59_Percent, SUM(CASE WHEN T.profile_complete between 60 and 69 THEN 1 ELSE 0 END) as Band_60_69_Percent, SUM(CASE WHEN T.profile_complete between 70 and 79 THEN 1 ELSE 0 END) as Band_70_79_Percent, SUM(CASE WHEN T.profile_complete between 80 and 89 THEN 1 ELSE 0 END) as Band_80_89_Percent, SUM(CASE WHEN T.profile_complete between 90 and 99 THEN 1 ELSE 0 END) as Band_90_99_Percent, SUM(CASE WHEN T.profile_complete = 100 THEN 1 ELSE 0 END) as Band_100_Percent from (select sum(um.WEIGHT) + 46 as profile_complete, u.LOGIN_ID from tcuser.user u, tcuser.user_ad ua, tcuser.USER_WIDGETS uw, tcadmin.WIDGET_MASTER um where ua.last_modified_time between char((current date - 1 day),ISO)||' 00:00:00.00' and char((current date - 1 day),ISO)||' 23:59:59.00' and u.LOGIN_ID = ua.LOGIN_ID and u.LOGIN_CREATE_DATE <> current date - 1 day and uw.LOGIN_SRL_NO = ua.LOGIN_SRL_NO and uw.resume_id = ua.ad_id and uw.WIDGET_STATUS_ID = 3 and um.WIDGET_ID = uw.WIDGET_ID Group by u.login_id ) T with ur

--export to /home/datareq/generic_etl/data_files/ACTIVE_RESUME_PROFILE_COMPLETE_FACT.txt of del modified by coldel, datesiso select date(current date - 1 day) LAST_LOGIN_DATE, SUM(CASE WHEN T.profile_complete between 0 and 49 THEN 1 ELSE 0 END) as Band_0_49_Percent, SUM(CASE WHEN T.profile_complete between 50 and 59 THEN 1 ELSE 0 END) as Band_50_59_Percent, SUM(CASE WHEN T.profile_complete between 60 and 69 THEN 1 ELSE 0 END) as Band_60_69_Percent, SUM(CASE WHEN T.profile_complete between 70 and 79 THEN 1 ELSE 0 END) as Band_70_79_Percent, SUM(CASE WHEN T.profile_complete between 80 and 89 THEN 1 ELSE 0 END) as Band_80_89_Percent, SUM(CASE WHEN T.profile_complete between 90 and 99 THEN 1 ELSE 0 END) as and_90_99_Percent, SUM(CASE WHEN T.profile_complete = 100 THEN 1 ELSE 0 END) as Band_100_Percent from (select sum(um.WEIGHT) + 46 as profile_complete, u.LOGIN_ID from tcuser.user u, tcuser.user_ad ua, tcuser.USER_WIDGETS uw, tcadmin.WIDGET_MASTER um where u.last_login_date between current date - 31 day and current date - 1 day and ua.login_id = u.login_id and uw.LOGIN_SRL_NO = ua.LOGIN_SRL_NO and uw.resume_id = ua.ad_id and uw.WIDGET_STATUS_ID = 3 and um.WIDGET_ID = uw.WIDGET_ID Group by u.login_id ) T with ur

export to /home/datareq/generic_etl/data_files/new_resume_profile_complete_widgets_dist_fact.txt of del modified by coldel, datesiso select T.LOGIN_CREATE_DATE, T.PROFILE_COMPLETENESS, UW1.WIDGET_ID, count(distinct UW1.LOGIN_SRL_NO) USER_COUNT from (select CASE WHEN (sum(um.WEIGHT) + 46) between 0 and 49 then '0 - 49%' WHEN (sum(um.WEIGHT) + 46) between 50 and 59 then '50 - 59%' WHEN (sum(um.WEIGHT) + 46) between 60 and 69 then '60 - 69 %' WHEN (sum(um.WEIGHT) + 46) between 70 and 79 then '70 - 79%' WHEN (sum(um.WEIGHT) + 46) between 80 and 89 then '80 - 89%' WHEN (sum(um.WEIGHT) + 46) between 90 and 99 then '90 - 99%' ELSE '100%' END as PROFILE_COMPLETENESS, u.LOGIN_SRL_NO, u.LOGIN_CREATE_DATE from tcuser.user u, tcuser.user_ad ua, tcuser.USER_WIDGETS uw, tcadmin.WIDGET_MASTER um where u.LOGIN_CREATE_DATE = current date - 1 day and ua.login_id = u.login_id and uw.LOGIN_SRL_NO = ua.LOGIN_SRL_NO and uw.resume_id = ua.ad_id and uw.WIDGET_STATUS_ID = 3 and um.WIDGET_ID = uw.WIDGET_ID Group by u.LOGIN_SRL_NO, u.LOGIN_CREATE_DATE ) T, USER_WIDGETS UW1 where UW1.login_srl_no= T.login_srl_no Group by T.LOGIN_CREATE_DATE, T.Profile_Completeness, UW1.WIDGET_ID with ur

export to /home/datareq/generic_etl/data_files/edit_resume_profile_complete_widgets_dist_fact.txt of del modified by coldel, datesiso select T.MODIFY_DATE, T.Profile_Completeness, UW1.WIDGET_ID, count(distinct UW1.LOGIN_SRL_NO) USER_COUNT from (select CASE WHEN (sum(um.WEIGHT) + 46) between 0 and 49 then '0 - 49%' WHEN (sum(um.WEIGHT) + 46) between 50 and 59 then '50 - 59%' WHEN (sum(um.WEIGHT) + 46) between 60 and 69 then '60 - 69 %' WHEN (sum(um.WEIGHT) + 46) between 70 and 79 then '70 - 79%' WHEN (sum(um.WEIGHT) + 46) between 80 and 89 then '80 - 89%' WHEN (sum(um.WEIGHT) + 46) between 90 and 99 then '90 - 99%' ELSE '100%' END as Profile_Completeness, u.LOGIN_SRL_NO, DATE(ua.LAST_MODIFIED_TIME) MODIFY_DATE from tcuser.user u, tcuser.user_ad ua, tcuser.USER_WIDGETS uw, tcadmin.WIDGET_MASTER um where ua.last_modified_time between char((current date - 1 day),ISO)||' 00:00:00.00' and     char((current date - 1 day),ISO)||' 23:59:59.00' and u.LOGIN_ID = ua.LOGIN_ID and u.LOGIN_CREATE_DATE <> current date - 1 day and uw.LOGIN_SRL_NO = ua.LOGIN_SRL_NO and uw.resume_id = ua.ad_id and uw.WIDGET_STATUS_ID = 3 and um.WIDGET_ID = uw.WIDGET_ID Group by u.LOGIN_SRL_NO, DATE(ua.LAST_MODIFIED_TIME) ) T, USER_WIDGETS UW1 where UW1.login_srl_no= T.login_srl_no Group by T.MODIFY_DATE, T.Profile_Completeness, UW1.WIDGET_ID with ur	
