#!/bin/ksh
set -x

cd $HOME/generic_etl/ksh_scripts

input=$3
isFile=`echo $input | egrep -i '\.txt|\.log|\.cron'`

if [[ $isFile != "" ]]; then
    input_file=`cat $input`
    perl $HOME/generic_etl/ksh_scripts/mail2.pl "$1" " $2" "$input_file"
else
     perl $HOME/generic_etl/ksh_scripts/mail2.pl "$1" " $2"  "$3"
fi
exit 1

